version: "3.9"
services:
  database:
    image: postgres
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
